<?php

namespace InfoCert\Top\OnboardingService;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'properties' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Properties',
            'property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Property',
            'string-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\String_property',
            'date-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Date_property',
            'boolean-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Boolean_property',
            'number-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Number_property',
            'properties-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Properties_property',
            'string-list-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\String_list_property',
            'boolean-list-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Boolean_list_property',
            'number-list-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Number_list_property',
            'date-list-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Date_list_property',
            'properties-list-property' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Properties_list_property',
            'identity-assertion' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Identity_assertion',
            'statements' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Statements',
            'claimer' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Claimer',
            'statement' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Statement',
            'subject' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Subject',
            'error' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Error',
            'documents' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Documents',
            'document' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Document',
            'document-policy' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Document_policy',
            'content' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Content',
            'composition-policy' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Composition_policy',
            'signature-policy' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signature_policy',
            'signature-fields' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signature_fields',
            'keyword-signature-fields' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Keyword_signature_fields',
            'position-signature-fields' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Position_signature_fields',
            'signature-field' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signature_field',
            'keyword-signature-field' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Keyword_signature_field',
            'position-signature-field' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Position_signature_field',
            'archiving-policy' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Archiving_policy',
            'attributes' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Attributes',
            'attribute' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Attribute',
            'graph-signature-document-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Graph_signature_document_info',
            'graph-signature-fields' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Graph_signature_fields',
            'graph-signature-field-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Graph_signature_field_info',
            'documents-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Documents_info',
            'document-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Document_info',
            'signature-field-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signature_field_info',
            'legal-id' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Legal_id',
            'person' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Person',
            'personal-data' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Personal_data',
            'contact-details' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Contact_details',
            'address' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Address',
            'identity-document-data' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Identity_document_data',
            'dossier-process-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_process_info',
            'signers' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signers',
            'signer-process-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signer_process_info',
            'dossier-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_info',
            'dossier-status' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_status',
            'signer-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signer_info',
            'clauses' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Clauses',
            'clause-result' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Clause_result',
            'certificate-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Certificate_info',
            'dossier-action-result' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_action_result',
            'dossier-record' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_record',
            'webid-service-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Webid_service_info',
            'certificate' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Certificate',
            'rao' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Rao',
            'dossier' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier',
            'signer' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signer',
            'dossier-creation-info' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_creation_info',
            'tokens' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Tokens',
            'token' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Token',
            'signer-status' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Signer_status',
            'identifications-status' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Identifications_status',
            'task-status' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Task_status',
            'dossier-result-set' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossier_result_set',
            'dossiers' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Dossiers',
            'getNewToken' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetNewToken',
            'getNewTokenResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetNewTokenResponse',
            'addDocumentsEx' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AddDocumentsEx',
            'number' => '\\InfoCert\\Top\\OnboardingService\\StructType\\Number',
            'addDocumentsExResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AddDocumentsExResponse',
            'abortDossier' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AbortDossier',
            'abortDossierResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AbortDossierResponse',
            'sendEventToSigner' => '\\InfoCert\\Top\\OnboardingService\\StructType\\SendEventToSigner',
            'sendEventToSignerResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\SendEventToSignerResponse',
            'addDocuments' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AddDocuments',
            'addDocumentsResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AddDocumentsResponse',
            'sendEventToDocument' => '\\InfoCert\\Top\\OnboardingService\\StructType\\SendEventToDocument',
            'sendEventToDocumentResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\SendEventToDocumentResponse',
            'getDossierByReservationCode' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossierByReservationCode',
            'getDossierByReservationCodeResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossierByReservationCodeResponse',
            'getDossier' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossier',
            'getDossierResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossierResponse',
            'getWebidServiceInfo' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetWebidServiceInfo',
            'getWebidServiceInfoResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetWebidServiceInfoResponse',
            'getDossierStatus' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossierStatus',
            'getDossierStatusResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossierStatusResponse',
            'cadesSign' => '\\InfoCert\\Top\\OnboardingService\\StructType\\CadesSign',
            'cadesSignResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\CadesSignResponse',
            'createDossier' => '\\InfoCert\\Top\\OnboardingService\\StructType\\CreateDossier',
            'createDossierResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\CreateDossierResponse',
            'assertIdentity' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AssertIdentity',
            'assertIdentityResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AssertIdentityResponse',
            'getSignerStatus' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetSignerStatus',
            'getSignerStatusResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetSignerStatusResponse',
            'assertAuthorization' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AssertAuthorization',
            'assertAuthorizationResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\AssertAuthorizationResponse',
            'updateSigner' => '\\InfoCert\\Top\\OnboardingService\\StructType\\UpdateSigner',
            'updateSignerResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\UpdateSignerResponse',
            'getDossiersByBusinessId' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossiersByBusinessId',
            'getDossiersByBusinessIdResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\GetDossiersByBusinessIdResponse',
            'sendEventToDossier' => '\\InfoCert\\Top\\OnboardingService\\StructType\\SendEventToDossier',
            'sendEventToDossierResponse' => '\\InfoCert\\Top\\OnboardingService\\StructType\\SendEventToDossierResponse',
        );
    }
}
